import os
from dotenv import load_dotenv

# Load .env file at the very beginning
if load_dotenv():
    print("APP.PY (MAIN): .env file loaded successfully.")
else:
    print("APP.PY (MAIN): .env file not found.")

import streamlit as st

# Import tab rendering functions
from tab1_new_enquiry import render_tab1
from tab2_manage_itinerary import render_tab2
from tab3_vendor_quotation import render_tab3

# Import sidebar rendering function
from sidebar import render_sidebar # NEW IMPORT

# --- CONFIGURATION ---
QUOTATIONS_BUCKET_NAME = "quotations"

st.set_page_config(layout="wide")
st.title("🤖 AI-Powered Travel Automation MVP")

# --- Initialize session state variables - centralized here ---
# This needs to happen before the sidebar is rendered if the sidebar depends on them.
# Global AI Provider (initialize before sidebar render)
if 'selected_ai_provider' not in st.session_state:
    st.session_state.selected_ai_provider = "OpenRouter" # Default

# Tab 1 & 2 shared states
if 'selected_enquiry_id' not in st.session_state:
    st.session_state.selected_enquiry_id = None
if 'current_ai_suggestions' not in st.session_state:
    st.session_state.current_ai_suggestions = None
if 'current_ai_suggestions_id' not in st.session_state:
    st.session_state.current_ai_suggestions_id = None
if 'itinerary_loaded_for_tab2' not in st.session_state:
    st.session_state.itinerary_loaded_for_tab2 = None

# Tab 3 specific states
if 'selected_enquiry_id_tab3' not in st.session_state:
    st.session_state.selected_enquiry_id_tab3 = None
if 'tab3_enquiry_details' not in st.session_state:
    st.session_state.tab3_enquiry_details = None
if 'tab3_client_name' not in st.session_state:
    st.session_state.tab3_client_name = "Valued Client"
if 'tab3_itinerary_info' not in st.session_state:
    st.session_state.tab3_itinerary_info = None
if 'tab3_vendor_reply_info' not in st.session_state:
    st.session_state.tab3_vendor_reply_info = None

# For managing the currently generated/loaded quotation in Tab 3
if 'tab3_current_quotation_db_id' not in st.session_state:
    st.session_state.tab3_current_quotation_db_id = None
if 'tab3_current_pdf_storage_path' not in st.session_state:
    st.session_state.tab3_current_pdf_storage_path = None
if 'tab3_current_docx_storage_path' not in st.session_state:
    st.session_state.tab3_current_docx_storage_path = None

# For holding locally generated bytes for download buttons (current session)
if 'tab3_quotation_pdf_bytes' not in st.session_state:
    st.session_state.tab3_quotation_pdf_bytes = None
if 'tab3_quotation_docx_bytes' not in st.session_state:
    st.session_state.tab3_quotation_docx_bytes = None

# Success/message flags
if 'show_quotation_success_tab3' not in st.session_state:
    st.session_state.show_quotation_success_tab3 = False
if 'vendor_reply_saved_success_message' not in st.session_state:
    st.session_state.vendor_reply_saved_success_message = None


# --- Render Sidebar ---
# The render_sidebar function will manage the 'selected_ai_provider' session state.
render_sidebar() # CALL THE SIDEBAR FUNCTION HERE

# --- Tab Definitions ---
tab1, tab2, tab3 = st.tabs([
    "📝 New Enquiry",
    "🔍 Manage Enquiries & Itinerary",
    "✍️ Add Vendor Reply & Generate Quotation"
])

with tab1:
    render_tab1()

with tab2:
    render_tab2()

with tab3:
    render_tab3(QUOTATIONS_BUCKET_NAME_param=QUOTATIONS_BUCKET_NAME)